/* eslint-disable import/prefer-default-export */
export const FETCHING_RESTAURANT = 'FETCHING_RESTAURANT';
export const FETCHING_RESTAURANT_SUCCESS = 'FETCHING_RESTAURANT_SUCCESS';
export const FETCHING_RESTAURANT_ERROR = 'FETCHING_RESTAURANT_ERROR';

export const FETCHING_RESTAURANT_BY_ID = 'FETCHING_RESTAURANT_BY_ID';
export const FETCHING_RESTAURANT_BY_ID_SUCCESS =
  'FETCHING_RESTAURANT_BY_ID_SUCCESS';
export const FETCHING_RESTAURANT_BY_ID_ERROR =
  'FETCHING_RESTAURANT_BY_ID_ERROR';
